### ISSUE TITLE
Feature discoverability

### ISSUE THREAD

**Issue by vemv** [clojure-lsp/lein-clojure-lsp#3]
Hi!

I'd be interested in giving this plugin some serious team usage.

The readme links to https://clojure-lsp.io/api/ which is mostly empty?

My understanding is that when you talk about "features" they are these? https://github.com/clojure-lsp/clojure-lsp/tree/9c8d034b2aa6668d7c287f0bdeb8648c1810aa32/lib/src/clojure_lsp/feature

Would it be possible to generate doc automatically for them? This table appears to have the adequate format https://clojure-lsp.io/features/#clojure-lsp-extra-commands, but I guess it only reflects the _extra_ commands.

Cheers - V

**Comment by ericdallo** [comment]
@vemv no, the current clojure-lsp API only support [these features](https://cljdoc.org/d/com.github.clojure-lsp/clojure-lsp/2022.07.24-18.25.43/api/clojure-lsp.api), so the lein plugin is only a entrypoint for lein to access that API

**Comment by vemv** [comment]
Alright, sounding good!

**Comment by ericdallo** [comment]
Closing this as we have now more [detailed doc about the API](https://clojure-lsp.io/api/what-is-it/).

**Comment by vemv** [comment]
Awesome, thank you!
